name: Ubuntu
on: [push, workflow_dispatch]

concurrency:
  group: ubuntu-ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        racket-variant: ['CS']
        racket-version: ['8.6', '8.10', '8.14', '8.18', 'stable', 'current']
    runs-on: ${{ matrix.os }}
    name: OS ${{ matrix.os }} / Racket ${{ matrix.racket-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.15
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}

    - name: Install LLVM
      uses: ZhongRuoyu/setup-llvm@v0
      with:
        llvm-version: 22

    - name: Install libssl
      run: |
        sudo apt install -y libssl-dev

    - name: Version info
      run: |
        clang --version
        gcc --version

    # Temporary: install the next branch of a86 while this is in development
    # Once merged in main, remove this and let it grab main branch by default
    - name: Install a86 next branch
      run: |
        raco pkg install --auto 'https://github.com/cmsc430/a86.git?#next'

    - name: Install langs package
      run: |
        raco pkg install --auto ../langs/

    - name: Run tests
      run: |
        xvfb-run raco test -p langs
